from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Dict


class BaseLLMProvider(ABC):
    """Abstraction layer to keep model providers swappable."""

    @abstractmethod
    def generate_json(self, system_prompt: str, user_prompt: str) -> Dict[str, Any]:
        """Return a structured JSON object generated by the provider."""
        raise NotImplementedError
